
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async healthCheck() : Promise<Result<AppHealth, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("health_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authRegisterStart(email: string, displayName: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_register_start", { email, displayName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authVerifyEmail(email: string, code: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_verify_email", { email, code }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authRegisterComplete(registrationToken: string, displayName: string) : Promise<Result<AuthResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_register_complete", { registrationToken, displayName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authLogin() : Promise<Result<AuthResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_login") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authRefresh() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_refresh") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authLogout() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_logout") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authRecoverStart(email: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_recover_start", { email }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authRecoverVerify(email: string, code: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_recover_verify", { email, code }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authRecoverComplete(recoveryToken: string) : Promise<Result<AuthResult, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_recover_complete", { recoveryToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authCheckIdentity() : Promise<Result<boolean, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_check_identity") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authGetPublicKey() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_get_public_key") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initiate WebSocket connection. Obtains a ticket and connects.
 */
async wsConnect() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ws_connect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Gracefully disconnect the WebSocket.
 */
async wsDisconnect() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ws_disconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Query current connection state.
 */
async wsGetState() : Promise<Result<WsConnectionState, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ws_get_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Subscribe to a channel's real-time events.
 */
async wsSubscribe(channelId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ws_subscribe", { channelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unsubscribe from a channel's events.
 */
async wsUnsubscribe(channelId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ws_unsubscribe", { channelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a typing indicator for a channel.
 */
async wsSendTyping(channelId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ws_send_typing", { channelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send an encrypted message to a channel.
 * 
 * Inserts an optimistic local message with status="pending", then sends via WebSocket.
 * Encryption per-device will be wired in once the member/device directory is available.
 */
async sendMessage(channelId: string, plaintext: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_message", { channelId, plaintext }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Edit a previously sent message.
 * 
 * Updates local cache and FTS, then sends the edit via WebSocket.
 */
async editMessage(channelId: string, messageId: string, newPlaintext: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("edit_message", { channelId, messageId, newPlaintext }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a message (soft-delete locally, notify server).
 */
async deleteMessage(channelId: string, messageId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_message", { channelId, messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retry decryption of a previously failed message.
 * 
 * For SessionNotFound/SessionCorrupted: re-fetch pre-key bundle,
 * establish new session, then attempt decryption with retained ciphertext.
 */
async retryDecrypt(messageId: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_decrypt", { messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start or retrieve a DM conversation with a user.
 * 
 * 1. Check local cache for existing DM channel with this user
 * 2. If found locally, return its DmChannelId
 * 3. If not found locally, call the server to create/find the DM
 * 4. Cache the DM channel locally
 * 5. Return the DmChannelId
 */
async startDm(userId: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_dm", { userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all DM conversations for the current user.
 * 
 * Returns DM channels sorted by most recent message, fetched from local cache.
 * On first load or cache miss, fetches from server and populates cache.
 */
async listDms() : Promise<Result<DmChannelInfo[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_dms") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a message in a DM channel.
 * 
 * Inserts an optimistic local message with status="pending", then sends via WebSocket.
 */
async sendDmMessage(dmChannelId: string, plaintext: string) : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_dm_message", { dmChannelId, plaintext }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppError = { message: string }
export type AppHealth = { version: string; db_status: string }
export type AuthResult = { user_id: string; public_key: string; device_id: string }
/**
 * DM channel info returned to the frontend.
 */
export type DmChannelInfo = { id: string; participantIds: string[]; lastMessagePreview: string | null; lastMessageAt: string | null; unreadCount: number }
/**
 * All possible states of the WebSocket connection.
 * Stored in Arc<RwLock<WsConnectionState>> as Tauri managed state.
 * Every state transition emits a `ws:state` Tauri event to the frontend.
 */
export type WsConnectionState = { status: "Disconnected" } | { status: "Connecting"; attempt: number } | { status: "Connected" } | { status: "Authenticated" } | { status: "Reconnecting"; attempt: number; next_retry_ms: number } | { status: "Failed"; reason: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
